export const videos = [
  {
    id: 1,
    intro: "Even if we lose, I want us to go for the win!...",
    name: "Even if we lose, I want us to go for the win! | Dinesh Karthik meets Virat Kohli | Full interview",
    url: "https://youtu.be/RoHEZmHZxzM",
    duration: "33:44",
    channel: "Sky Sports Cricket",
    logo: "https://i.ibb.co/z8JH30D/vi.jpg",
    thumbnail: "https://i.ibb.co/SQbCLBC/virat-dk.jpg",
    verified: true,
  },
  {
    id: 2,
    intro: "Wordpress is giving you a business opportunity...",
    name: "Wordpress is giving you a business opportunity",
    url: "https://youtu.be/1fGrZtKkjn8",
    duration: "8:27",
    channel: "Hitesh Choudhary",
    logo: "https://i.ibb.co/5vcrY6q/hc.jpg",
    thumbnail: "https://i.ibb.co/8DnCgDG/hct.jpg",
    verified: true,
  },
  {
    id: 3,
    intro: "What to do in college? Part II: Actionable Items...",
    name: "What to do in college? Part II: Actionable Items",
    url: "https://youtu.be/TSzgIOXxOZk",
    duration: "7:42",
    channel: "Tanay Pratap",
    logo: "https://i.ibb.co/gWQHfYv/tp.jpg",
    thumbnail: "https://i.ibb.co/SwVBTRL/Tpt.jpg",
    verified: true,
  },
  {
    id: 4,
    intro: "Animals That Can Kill Themselves...",
    name: "Animals That Can Kill Themselves",
    url: "https://youtu.be/h6NAJygd3Wg",
    duration: "8:01",
    channel: "WATOP",
    logo: "https://i.ibb.co/zFJH81H/ani-watop.jpg",
    thumbnail: "https://i.ibb.co/hD67zyD/animal.jpg",
    verified: true,
  },
  {
    id: 5,
    intro: "Facing 100 MPH BOWLING and hitting 100m sixes!...",
    name: "Facing 100 MPH BOWLING and hitting 100m sixes! Can the weCricket boys SURVIVE!?",
    url: "https://youtu.be/ZSEi5WiWPyY",
    duration: "6:39",
    channel: "ESPNcricinfo",
    logo: "https://i.ibb.co/Y7FZnkR/espn.jpg",
    thumbnail: "https://i.ibb.co/DV175pz/espnt.jpg",
    verified: true,
  },
  {
    id: 6,
    intro: "Build 5 Projects With HTML, CSS & JavaScript...",
    name: "Build 5 Projects With HTML, CSS & JavaScript",
    url: "https://youtu.be/JkeyKeK3V24",
    duration: "1:51:00",
    channel: "Traversy Media",
    logo: "https://i.ibb.co/K5mJWDZ/tv.jpg",
    thumbnail: "https://i.ibb.co/DwpZZRH/tvmt.jpg",
    verified: true,
  },
  {
    id: 7,
    intro: "Install Prettier in VS Code...",
    name: "Install Prettier in VS Code",
    url: "https://youtu.be/Gmz27agvLYg",
    duration: "5:51",
    channel: "Code Wizard",
    logo: "https://i.ibb.co/BcSy7m6/pretc.jpg",
    thumbnail: "https://i.ibb.co/Wk9DXMK/Pret.jpg",
    verified: true,
  },
  {
    id: 8,
    intro: "Suryakumar Yadav reminisces his brutal...",
    name: "Suryakumar Yadav reminisces his brutal knock in the Season 1 final",
    url: "https://youtu.be/ONN-wXyH_Gw",
    duration: "2:08",
    channel: "T20 Mumbai",
    logo: "https://i.ibb.co/V2qwsqY/suryac.jpg",
    thumbnail: "https://i.ibb.co/XJR00N5/suryat.jpg",
    verified: true,
  },
  {
    id: 9,
    intro: "Ravi Kumar takes home silver |...",
    name: "Ravi Kumar takes home silver | #Tokyo2020 Highlights",
    url: "https://youtu.be/5TflfS8FsNs",
    duration: "3:05",
    channel: "Olympics",
    logo: "https://i.ibb.co/Dw4KK2z/olympicsc.jpg",
    thumbnail: "https://i.ibb.co/7SP5BNg/olympicst.jpg",
    verified: true,
  },
  {
    id: 10,
    intro: "Full React Tutorial #19 - Handling...",
    name: "Full React Tutorial #19 - Handling Fetch Errors",
    url: "https://youtu.be/DTBta08fXGU",
    duration: "7:38",
    channel: "The Net Ninja",
    logo: "https://i.ibb.co/ZBxvYNR/ninjac.jpg",
    thumbnail: "https://i.ibb.co/cF8vFJY/ninjat.jpg",
    verified: true,
  },
  {
    id: 11,
    intro: "Dinesh Karthik hits 22 runs off Rubel...",
    name: "Dinesh Karthik hits 22 runs off Rubel Hossain - 19th over of Nidahas Trophy Final",
    url: "https://youtu.be/pPwVCIvO7tg",
    duration: "5:48",
    channel: "Sri Lanka Cricket",
    logo: "https://i.ibb.co/RTtrtmR/dkc.jpg",
    thumbnail: "https://i.ibb.co/PQWYPXk/dkt.jpg",
    verified: true,
  },
  {
    id: 12,
    intro: "Neeraj Chopra qualifies for final...",
    name: "Neeraj Chopra qualifies for final | #Tokyo2020 Highlights",
    url: "https://youtu.be/v5HgIOsw6mk",
    duration: "3:05",
    channel: "Olympics",
    logo: "https://i.ibb.co/Dw4KK2z/olympicsc.jpg",
    thumbnail: "https://i.ibb.co/8zZJM5P/niravt.jpg",
    verified: true,
  },
  {
    id: 13,
    intro: "Neymar penalty seals gold for hosts...",
    name: "Neymar penalty seals gold for hosts | Rio 2016 Olympic Games",
    url: "https://youtu.be/-Jmjn_dJt_4",
    duration: "2:10",
    channel: "Olympics",
    logo: "https://i.ibb.co/Dw4KK2z/olympicsc.jpg",
    thumbnail: "https://i.ibb.co/znrzKNm/neymart.jpg",
    verified: true,
  },
  {
    id: 14,
    intro: "5 productivity tips to achieve more in life",
    name: "5 productivity tips to achieve more in life",
    url: "https://youtu.be/Y-E-oNqPIHc",
    duration: "5:42",
    channel: "Tanay Pratap",
    logo: "https://i.ibb.co/gWQHfYv/tp.jpg",
    thumbnail: "https://i.ibb.co/s2BCfpg/tptp.jpg",
    verified: true,
  },
  {
    id: 15,
    intro: "Lasith Malinga's four-ball 4-wicket hat-trick",
    name: "Lasith Malinga's four-ball 4-wicket hat-trick",
    url: "https://youtu.be/nclPaVQmCHc",
    duration: "3:55",
    channel: "Sri Lanka Cricket",
    logo: "https://i.ibb.co/RTtrtmR/dkc.jpg",
    thumbnail: "https://i.ibb.co/2NLRcwX/malingat.jpg",
    verified: true,
  },
  {
    id: 16,
    intro: "Sharma Stars In Thriller | SUPER OVER...",
    name: "Sharma Stars In Thriller | SUPER OVER REPLAY | BLACKCAPS v India - 3rd T20, 2020",
    url: "https://youtu.be/PJutG613i7E",
    duration: "6:29",
    channel: "NZC",
    logo: "https://i.ibb.co/rpn0Hzg/rohitc.jpg",
    thumbnail: "https://i.ibb.co/XDt6rhw/rohit.jpg",
    verified: true,
  },
  {
    id: 17,
    intro: "When Sport Players Meet Luck",
    name: "When Sport Players Meet Luck",
    url: "https://youtu.be/UannexQjNEo",
    duration: "4:29",
    channel: "STROPS",
    logo: "https://i.ibb.co/FhWgkyy/bikec.jpg",
    thumbnail: "https://i.ibb.co/VCD7Mxv/biket.jpg",
    verified: true,
  },
  {
    id: 18,
    intro: "Modern JavaScript Tutorial #1 - Intro & Setup",
    name: "Modern JavaScript Tutorial #1 - Intro & Setup",
    url: "https://youtu.be/iWOYAxlnaww",
    duration: "12:25",
    channel: "The Net Ninja",
    logo: "https://i.ibb.co/ZBxvYNR/ninjac.jpg",
    thumbnail: "https://i.ibb.co/q7dvRwM/ninjamt.jpg",
    verified: true,
  },
  {
    id: 19,
    intro: "CSS Crash Course For Absolute Beginners",
    name: "CSS Crash Course For Absolute Beginners",
    url: "https://youtu.be/yfoY53QXEnI",
    duration: "1:25",
    channel: "Traversy Media",
    logo: "https://i.ibb.co/K5mJWDZ/tv.jpg",
    thumbnail: "https://i.ibb.co/WfvV0zd/csst.jpg",
    verified: true,
  },
  {
    id: 20,
    intro: "India's comeback goals vs Germany 🏑...",
    name: "India's comeback goals vs Germany 🏑 | #Tokyo2020 Highlights",
    url: "https://youtu.be/f_Hr5CCaMqw",
    duration: "0:35",
    channel: "Olympics",
    logo: "https://i.ibb.co/Dw4KK2z/olympicsc.jpg",
    thumbnail: "https://i.ibb.co/WcsdGgV/hockeyt.jpg",
    verified: true,
  },
];
